name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    # TODO: Split these into seperate jobs that can run in parallel
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent
      - name: Lint
        run: yarn lint:all
      - name: Format
        run: yarn format:check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
